In [1]:
import numpy as np
import scipy as sp
import time
import math

import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression


np.set_printoptions(precision=2)

In [2]:
def getkjp(r,q,l):
    m = (r-1)//2
    ip = q*l+1
    k = ip//r
    j = ip%r
    if j < m+1:
        return j
    else:
        return r-j
def getkjm(r,q,l):
    m = (r-1)//2
    ip = q*l-1
    k = ip//r
    j = ip%r
    if j < m+1:
        return j
    else:
        return r-j

def RT1s(r,q):
    t0 = time.time()
    m = (r-1)//2
    #print(m)
    mat = np.zeros(shape=(m,m))
    for l in range(0,m):
        col = np.zeros(shape=(m,))
        jp = getkjp(r,q,l)
        jm = getkjm(r,q,l)
        if jp == jm == 1:
            col[0] = 1
        if jm == 0 and jp == 2:    
            col[jp-1] = 1
        if jp == 0 and jm == 2:    
            col[jm-1] = -1
        if jp + jm > 2:
            col[jp-1] = 1
            col[jm-1] =- 1
        mat[:,l] = col
    return mat

def qp6Bound(q):
    nums = []
    if (q%2) == 0:
        for r in range(3,q+3+1,2):
            if math.gcd(r,q) == 1:
                nums.append(r)
    else:
        for r in range(3,q+6+1,2):
            if math.gcd(r,q) == 1:
                nums.append(r)
    return nums

def qm3Bound(q):
    nums = []
    if q%2 == 0:
        for r in range(3,q,2):
            if math.gcd(r,q) == 1:
                nums.append(r)
    return nums

In [7]:
for r in range(13,15,2):
    if math.gcd(r,6) == 1:
        print(RT1s(r,6))
        print("---------------------------------------")

[[ 1.  0.  0.  0.  1.  0.]
 [ 0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0. -1. -1.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0. -1.  0.  0.  0.  1.]
 [ 0.  1.  0.  1.  0.  0.]]
---------------------------------------


In [8]:
vals = [r  for r in range(3,75,2) if math.gcd(r,q) == 1]
print(vals)

[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73]


In [11]:
for q in range(2,135,2):
    print("q = %s" % q)
    print("____")
    rvals = qp6Bound(q)
    #rvals = [r  for r in range(3,575,2) if math.gcd(r,q) == 1]
    for r in rvals[1:]:
        R = RT1s(r,q)
        cols = []
        for i in range(1,R.shape[1]):
            c = sum(R[:,i])
            cols.append(c)
        #print(cols)
        if int(sum(R[1]))%2 > 0:
            print("r = %s" % r)
            print(R)
            print("--------------------------")
    print("-------------------------------------------------------------------------------")

q = 2
____
r = 5
[[ 1. -1.]
 [ 0.  1.]]
--------------------------
-------------------------------------------------------------------------------
q = 4
____
r = 5
[[ 1.  0.]
 [ 0. -1.]]
--------------------------
-------------------------------------------------------------------------------
q = 6
____
r = 7
[[ 1.  0.  1.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
--------------------------
-------------------------------------------------------------------------------
q = 8
____
r = 5
[[ 1.  1.]
 [ 0. -1.]]
--------------------------
r = 7
[[ 1.  0. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
--------------------------
-------------------------------------------------------------------------------
q = 10
____
-------------------------------------------------------------------------------
q = 12
____
r = 7
[[ 1.  1.  0.]
 [ 0.  0. -1.]
 [ 0. -1.  1.]]
--------------------------
-------------------------------------------------------------------------------
q = 14
____
r = 5
[[ 1.  0.]
 [ 0. -1.]]
------

r = 31
[[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]]
--------------------------
r = 33
[[ 1.  1.  0.

r = 41
[[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1. -1.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
  -1.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.
   0.  0.]
 [ 0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

[[ 1. -1.  0.]
 [ 0.  0.  1.]
 [ 0.  1. -1.]]
--------------------------
r = 17
[[ 1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0. -1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  1.]
 [ 0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  1.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  1.  0.  0.]]
--------------------------
r = 47
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  

-------------------------------------------------------------------------------
q = 112
____
r = 5
[[ 1. -1.]
 [ 0.  1.]]
--------------------------
r = 11
[[ 1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0.  0.  1. -1.  0.]]
--------------------------
r = 19
[[ 1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0. -1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  1.]
 [ 0.  0. -1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  1.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  1.  0.  0.  0.]]
--------------------------
r = 53
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
   1.  0.  0.  0

[[ 1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0. -1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  1.]
 [ 0.  0. -1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  1.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0. -1.  1.  0.  0.]


r = 63
[[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0